### ISSUE TITLE
fouten in pdf import 

### ISSUE THREAD

**Issue by erikwesselius** [now-inzichtelijk-nl/now-inzichtelijk-nl-website#1]
Beste @ansien, Allereerst mijn complimenten met het idee voor deze website en dank voor het vrijelijk beschikbaar stellen ervan. Superinteressant. Gisteren voor het eerst rondgekeken op de website en deze op Twitter gepromoot.

Ik dacht alle bedrijven in de gemeente Ede te hebben door te zoeken op Ede GLD, maar het blijkt dat dit niet het totaalplaatje is: vanochtend kocht ik gebak bij Patisserie Van Woerekom hier in Bennekom en ik vroeg me af hoeveel zij zouden hebben ontbvangen (ik weet dat deze pattissier bij evenementen (zoete) catering verzorgt). En inderdaad: Van Woerekom staat in het register, maar niet onder gemeente Ede, maar onder Bennekom (terwijl de aanvragen per gemeente worden afgehandeld). Deze inconsistentie ligt klaarblijkelijk bij de gemeenten die de gegevens bij de UWV aanleveren, maar er zou hier dus in jouw webzoekmachine nog een kleine verbeterslag te halen zijn door plaatsnamen die niet in de groslijst van NL gemeenten staan te herleiden tot een gemeente die wel op de lijst staat. Dit is een handmatige klus en ik wil daar wel bij helpen :-)

**Comment by ansien** [comment]
Dank voor je bericht, ik kom hier z.s.m. op terug!

**Comment by erikwesselius** [comment]
Overigens ook bijzonder dat een Italiaans bedrijf (ZEP SRL uit San Giorgio delle Pertiche) een beroep heeft gedaan op de Nederlandse NOW-subsidie. Het gaat om een echt bedrijf, maar ik zie geen relatie met Nederland: https://www.zep-italia.it/chisiamo

Ik heb intussen een lijst gevonden met de 355 gemeenten in Nederland. Overigens is het dan ook nog niet waterdicht. De grootste ontvanger in Bennekom (IPSS ENGINEERING B.V. | BENNEKOM | € 70.656) is helemaal niet in Bennekom of de gmeente Ede gevestigd, maar aan het Bronland op de Campus van de WUR, in de gemeente Wageningen. Een lokatie vlakbij Bennkom, dat weer wel.

**Comment by ansien** [comment]
Dag @erikwesselius,

Ik heb je berichten even doorgenomen. Ik denk persoonlijk dat het enorm veel werk gaat kosten om de 138 duizend records langs te lopen en (handmatig) aan te passen. Ook gezien je 2e bericht, wat het nog complexer maakt. En als straks de andere registers aangeleverd worden moet het daar potentieel ook weer aangepast worden...

Maar het zou inderdaad wel mooi zijn om dit allemaal goed inzichtelijk te krijgen per gemeente.
